### ISSUE TITLE
Provide a option to generate passwords

### ISSUE THREAD

**Issue by klausenbusk** [mozilla-lockwise/lockwise-addon#130]
A option to generate a strong password could be very useful, when signing up for new services.

Related issue: https://github.com/mozilla-lockbox/lockbox-android/issues/554

**Comment by dkout** [comment]
+1 on this! Imo this is main drawback when compared to alternatives. There is not much point in securely storing a password if it is short and easy to guess.

**Comment by klausenbusk** [comment]
It looks like this feature will be built into Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1548381

**Comment by Paradoxeuh** [comment]
From what I understand, the built-in function in Firefox depends on the <input> of the website. It would be nice to have the choice of generating a strong password no matter what.

**Comment by klausenbusk** [comment]
> From what I understand, the built-in function in Firefox depends on the of the website. It would be nice to have the choice of generating a strong password no matter what.

It works with all passwords fields:

https://wiki.mozilla.org/Toolkit:Password_Manager/Password_Generation
> Generate a single password format for all websites but allow the user to reveal and edit the password. Fill generated passwords via the two new UIs:
> * autocomplete on autocomplete="new-password" fields
> * context menu on any password field (even if it's not intended for new passwords)

**Comment by krzyk** [comment]
I have never seen password generator and I have it enabled in settings. So it doesn't work on any password field, I would say it never works on password fields (I have Nightly).

**Comment by cadeyrn** [comment]
> I have never seen password generator and I have it enabled in settings. So it doesn't work on any password field, I would say it never works on password fields (I have Nightly).

It works in Firefox Nightly, I just tested it a few moments ago. Please read the previous comment to understand how it works.

**Comment by Goddard** [comment]
Really need a consistent way to do it in lockwise so it looks the same in android, ios, and desktop.
