### ISSUE TITLE
Not possible to keyboard navigate into logins list on manage page

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockwise/lockwise-addon#173]
When just tabbing through the management page, it's not currently possible to send the keyboard focus into the list of logins. Seems you have to manually click on a login for keyboard focus to shift into the list.

Probably just need to make sure a tabindex is set on the list parent.

**Comment by sandysage** [comment]
time box to a couple of hours

**Comment by linuxwolf** [comment]
@6a68 did you say this is or is not still an issue?

**Comment by linuxwolf** [comment]
Tried this for myself, and I am able to navigation into – and out of – the left-side navigation list.  Closing as fixed.
