### ISSUE TITLE
The Lockbox doorhanger can no longer be opened if the "Enter master password" window is cancelled/dismissed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockwise/lockwise-addon#176]
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 67 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 67 version installed.
- Have the Lockbox 2.1.0 - alpha extension installed.
- Have a master password set in the browser.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Cancel the "Enter master password" window.
3. Click the Lockbox toolbar button and observe the behavior.

[Expected results]:
- The "Enter master password" window is triggered.

[Actual results]:
- Nothing happens.

[Notes]:
- Attached a screen recording with the issue:
![lockbox toolbar icon and master password](https://user-images.githubusercontent.com/19226534/56646292-f3e4ff80-6687-11e9-9dc3-248c642b5754.gif)

**Comment by mnoorenberghe** [comment]
This is specific to being installed in FIrefox and wouldn't be relevant to a future extension for other browsers.
