### ISSUE TITLE
The "Enter master password" window is displayed after each browser restart if Lockbox is installed and a master password is set

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockwise/lockwise-addon#177]
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 67 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 67.0 version installed.
- Have the Lockbox 2.1.0 - alpha extension installed.
- Have a master password set in the browser.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Observe the behavior.

[Expected results]:
- The "Enter master password" window is not displayed. It is displayed only when the Lockbox toolbar button is clicked or interact with a login form.

[Actual results]:
- The "Enter master password" window is displayed.

[Notes]:
- Attached a screen recording with the issue:
![master password after each restart](https://user-images.githubusercontent.com/19226534/56646633-98674180-6688-11e9-8d50-0148755dfc56.gif)

**Comment by mnoorenberghe** [comment]
This is specific to being installed in FIrefox and wouldn't be relevant to a future extension for other browsers.
