### ISSUE TITLE
Improvements to fluent usage

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/lockwise-addon#204]
Improve how Fluent is used in the addon to better help localizers out.

Summarized from a communique via @flodolo:

* brand names should be terms, not standard messages. You can add a section comment for them ([example](https://hg.mozilla.org/l10n/gecko-strings/file/default/browser/branding/official/brand.ftl))
* No need to add NOTE: to comments
* It would be nice to avoid unnecessarily new lines when the string is short
* We shouldn't have select expressions special casing 0 for something different from the other cases. We should have a string for the zero case, and handle the rest in the code. ([incorrect example](https://github.com/mozilla-lockbox/lockbox-addon/blob/master/src/locales/en-US/list.ftl#L44-L48))
* Section comment should be explanatory and help localizers.
* Resolve all the TODOs
* Add l10n reviewer to CODEOWNERS

## To Do

* [ ] Separate unlocalizable strings and localizable strings into separate files
* [x] Ensure the following are (unlocalizable) terms:
  - Firefox
  - (Firefox) Lockbox|Lockwise
  - (Firefox) Sync
* [x] Note that "Firefox Account" requires [special treatment](https://hg.mozilla.org/l10n/gecko-strings/file/default/browser/browser/branding/sync-brand.ftl#l11)
  - [x] Should use `-fxaccount-brand-name` message ID to align with other projects
* [x] Consistent use of the following **localizable** terms:
  - `add-on`
* [ ] Use self-explanatory placeables/slugs; e.g., `-fxlockwise-product-name` instead of `-product-name`
* [x] Consistent spacing of slugs and placeables; e.g. `{ $count }` and `{ -product-full-name }` instead of `{$count}` or `{product-full-name}`
* [x] Fix/add section names to be more descriptive of what/where the strings are used for
* [x] Remove references/pointers to (now nonexistent) [translation guidelines](https://www.mozilla.org/styleguide/communications/translation/)
* [x] Remove any "column alignment" spacers; e.g., do the following:
```
list-count = ( $count ->
  [one] { $count } entry
 *[other] { $count } entries
}
```
* [ ] Comment on (or otherwise remove) seemingly idential strings to help explain differences:
  - `connect-a-firefox-account` vs `connect-a-firefox-account-complete`
* [ ] Make sure the app/play store icons have separate LICENSE files
* [ ] Change the promo banner CTA string (`banner-promote-device .details` and `banner-promote-fxa .details`) to be one string with an infixed `<strong>` tag.
  - see bedrock examples listed [here](https://github.com/mozilla-lockwise/lockwise-addon/pull/209#issuecomment-490754969)

**Comment by flodolo** [comment]
One more thing: before we start localizing, we should figure out all the TODOs in the FTL files.
