### ISSUE TITLE
Update Promo styling as full-width component over the top of list and details

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-addon#207]
## Acceptance criteria
* should provide more emphasis to these 'call to actions' regardless of what the user is doing within the management interface
* the promo banner should always display until we prioritize #95
* should not show the close (X) button as provided in the designs

**Comment by 6a68** [comment]
Open question for @changecourse:

How should the layout change at smaller widths?

And a question for @sandysage:

What does it mean if the user dismisses the promo by clicking the 'x'? Do we hide it forever, just for the current session (until restart), or for a set period of time, like 2 weeks? Also, if the user dismisses one view (like, the FxA view), then signs in, should we show the mobile app upsell promo?

**Comment by sandysage** [comment]
Let's treat dismissing the promotion as it's own separate feature/functionality as found in #95. I'll respond in that ticket.

For now, dismiss capabilities is lower in the priority list for these layout changes since there are additional requirements we need to consider here.

**Comment by linuxwolf** [comment]
> For now, dismiss capabilities is lower in the priority list for these layout changes since there are additional requirements we need to consider here.

To be clear, this means:

* Always display the promo banner, and
* Remove/hide the close (X) button

**Comment by sandysage** [comment]
Correct. In fact, I'm updating the above requirements to capture those statements.

**Comment by 6a68** [comment]
FWIW, I already have the close button implemented in the WIP PR, with the behavior where it stays closed until the manage page is reloaded
