### ISSUE TITLE
Reflow Header Bar

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/lockwise-addon#210]
## Notables

* [x] Use "full logo w/ text" (alt text is full product name)
* [x] Move search from left-side list to title heading (centered)
* [x] Move "+" (add) from left-side list to title heading (right of search)
   - text is now "New Login"

## References
* [Invision](https://mozilla.invisionapp.com/share/EJRHBMEDKF8#/screens)
* Full logo ([svg](https://drive.google.com/file/d/1QXyFFw6wXIjqBJnbxpViSvp-vt8F_ZmV/view))
* Related to #206

**Comment by 6a68** [comment]
I've removed the 'logins' tab in the `desktop-ux` branch, would be a good starting point for the rest of this issue.

**Comment by linuxwolf** [comment]
Closed vis #214
