### ISSUE TITLE
Style cleanups for 5/10 release

### ISSUE THREAD

**Issue by meandavejustice** [mozilla-lockwise/lockwise-addon#225]
- [x] Sort Header – Arrow should be aligned to each label, rather than longest label
- [x] Search – Match active state to spec https://zpl.io/bWNeopM
- [x] Login Detail
  - [x] Login Detail – Match behavior of website address link to photon spec – https://design.firefox.com/photon/components/links.html 
  - [x] Login Detail – Update Edit Icon and icon colors `.item-summary__title___SnqUb` – set font weight to 500
- [x] Create New Login – Buttons misaligned and not sufficient padding, tooltip for website address not matching spec  https://zpl.io/andLDWA 
- [x] Create Login – match padding of Create Login (hr, header, and fields) to Login Detail
- [x] Edit Login – match padding of Create Login (header and fields) to Login Detail

**Comment by meandavejustice** [comment]
cc @sandysage @changecourse

**Comment by meandavejustice** [comment]
I'm working on the Sort Header section first

**Comment by 6a68** [comment]
@linuxwolf Hey, what's left to do for this bug?

**Comment by linuxwolf** [comment]
> @linuxwolf Hey, what's left to do for this bug?

Updated the checkboxes to reflect things that are truly done.  Since we have a tiny bit left to get done (l10n), we can discuss whether to try and fiinish the rest of the checkboxes.

**Comment by sandysage** [comment]
I'm moving the remaining checkboxes to another ticket so that they don't get lost. I think if the changes are approved then we can close this issue.
