### ISSUE TITLE
Pasting a link into the "Website Address" field automatically adds a "/" and the saved login is not recognized on the website

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-lockwise/lockwise-addon#238]
[Affected Versions]:
- Lockwise 2.2.0-alpha
- Firefox 67.0b19

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- The Lockwise 2.2.0-alpha add-on is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a website and copy the website's address. (e.g https://www.facebook.com)
3. Navigate to the Lockwise page and click the "New Login" button.
4. Paste the copied string into the "Website Address" field and fill the rest of the fields.
5. Save the login and launch it.
6. Observe the page.

[Expected results]:
- The website is displayed and the login is automatically filled.

[Actual results]:
- The saved login is not recognized by the website.

[Notes]:
- Pasting a link automatically adds a "/" at the end regardless of the used application.
- Attached a screen recording of the issue:
![Extra_slash](https://user-images.githubusercontent.com/40393891/57620987-fa81db00-7592-11e9-8c4f-89ad96634ee1.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Lockwise 2.2.1-alpha version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.14 and Arch Linux 4.12.
