### ISSUE TITLE
Passwords wrongly remain visible after clicking the "Show" button and switching logins

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-lockwise/lockwise-addon#253]
[Affected Versions]:
- Lockwise 2.2.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- The Lockwise 2.2.0-alpha add-on is installed.
- Have multiple logins saved.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockwise" toolbar button and click the "Open Lockwise" button.
3. Click the "Show" button from the password field.
4. Click on each of the saved logins.

[Expected results]:
- The passwords are hidden, except for the revealed one.

[Actual results]:
- The passwords from all the saved logins are visible.

[Notes]:
- The issue is not reproducible using the doorhanger.
- Attached a screen recording of the issue:
![revealed](https://user-images.githubusercontent.com/40393891/57933394-e6591900-78c5-11e9-81bd-d28e240fa487.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Lockwise 2.2.1-alpha version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.14 and Arch Linux 4.12.
