### ISSUE TITLE
Inactive scroll bars are wrongly displayed on the "Lockwise" onboarding page

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla-lockwise/lockwise-addon#268]
**[Affected Versions]:**
- Lockwise 2.2.1-alpha
- Firefox 67 and above

**[Affected Platforms]**
- All Windows
- All Mac
- All Linux

**[Perquisites]**
- Have the latest Firefox 67 version installed.
- Have the Lockwise 2.2.1 - alpha extension installed.
- Have at least one saved login.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockwise" toolbar button.
3. Click the "Open Lockwise" button.
4. Observe the "Lockwise" onboarding page.

**[Expected results]:**
- All the elements from the onboarding page are correctly displayed and rendered.

**[Actual results]:**
- Two inactive scroll bars, one vertical and one horizontal are displayed.

**[Notes]:**
- If the browser is resized to a bit more than half of the screen an active horizontal scroll bar is displayed under the inactive one.
- This issue is not reproducible if there are no saved logins.
- Attached a screen recording with the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/58175037-ed0dd480-7ca7-11e9-8f6e-240cf8c917e4.gif)

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the lockwise-signed.xpi (2.2.4) add-on on Windows 10 x64, Arch Linux and Mac 10.14.4 using Firefox Beta 68.0b11.
