### ISSUE TITLE
Pontoon can't commit to the repository

### ISSUE THREAD

**Issue by flodolo** [mozilla-lockwise/lockwise-addon#270]
I'm not exactly not sure what's happening, but:
1) If I run the add-on from the pontoon branch, it doesn't appear to be localized.
2) If I install the package from `npm run package`, it doesn't even work.

I tested the add-on 3 days ago and it was working (manually edited a string), I have no clue what changed.

CC @devinreams  @Pike

**Comment by flodolo** [comment]
If I copy over en-US and change a random English string it's picked up correctly. I bet you're barfing on parsing the Italian file…

**Comment by flodolo** [comment]
Actually, it looks like Pontoon is not writing to the repository. The only commit there is the test one I did.

**Comment by flodolo** [comment]
The branch looks protected. Did you folks change something after I tested stage?

```

May 23 05:12:19 mozilla-pontoon app/worker.1: To github.com:mozilla-lockwise/lockwise-addon.git 
May 23 05:12:19 mozilla-pontoon app/worker.1:  ! [remote rejected] pontoon -> pontoon (protected branch hook declined) 
May 23 05:12:19 mozilla-pontoon app/worker.1: error: failed to push some refs to 'git@github.com:mozilla-lockwise/lockwise-addon.git' 
May 23 05:12:19 mozilla-pontoon app/worker.1: Failed to sync translations for project lockwise-add-on due to commit error. 
```

**Comment by flodolo** [comment]
Tested with a manual copy, and the add-on is localized. Also double checked the project config on stage and prod, they're identical, so someone must have changed something in the repository settings.

**Comment by devinreams** [comment]
>May 23 05:12:19 mozilla-pontoon app/worker.1:  ! [remote rejected] pontoon -> pontoon (protected branch hook declined) 

@flodolo I marked the pontoon branch “protected” so it wouldn’t be deleted but may have had the committee/who can push setting too restrictive. Can you please try again?

**Comment by flodolo** [comment]
Since it was on prod, the cronjob kicked in the meantime
https://github.com/mozilla-lockwise/lockwise-addon/commits/pontoon

**Comment by devinreams** [comment]
Sorry for the footgun introduced as I attempted to prevent a future footgun. Thanks for the quick action
