### ISSUE TITLE
"Sort by" layout breaks with longer translation

### ISSUE THREAD

**Issue by flodolo** [mozilla-lockwise/lockwise-addon#273]
"Ordina per:" (Sort by:) is completely broken when there's a longer translation selected in the dropdown.

![Schermata 2019-05-23 alle 07 42 44](https://user-images.githubusercontent.com/3644868/58228347-b038f080-7d2e-11e9-9715-9645e480da84.png)

**Comment by linuxwolf** [comment]
Will need to discuss options with @mozilla-lockwise/ux to resolve this.
