### ISSUE TITLE
Feature request: Ask for computer password before displaying password

### ISSUE THREAD

**Issue by narFnarF** [mozilla-lockwise/lockwise-addon#288]
Having this addon installed makes it very easy to see my passwords if another user would have access to my computer for a short moment. I know that, at least on Windows, Chrome helps on this regard by asking for the computer password (the password of the currently logged in user). I'm wondering if a similar feature could be implemented in Lockwise.

I realize that the passwords can also be seen in Firefox's Settings without any more restrictions. In this context, we would also require Firefox itself to add this lock I'm proposing.  The difference is that the addon is very visible and accessible right in the toolbar, with just 1 click, unlike the main Firefox's Settings which require multiple clicks and scrolling to reach.

I know that the Master Password exist and would help... but that's yet another password to remember.

**How it would work**

- When trying to reveal a password, or when trying to copy it, the addon first ask the user to enter the computer password (current user password)
- If the user has no password, skip this. That computer is not secure anyway! :)

**Comment by feferna** [comment]
I agreed... I think the idea of the app is really interesting, but there is no way I am going to use it, if it is so easy to see my passwords in my PC. What if my PC get stolen, all my accounts will get hacked?

**Comment by whimboo** [comment]
This also applies to copying a password. Even with the master password set, it is not requested. That means that security wise I cannot use the add-on at the moment.

**Comment by whimboo** [comment]
Since the addon is part of Firefox Nightly now, see also https://bugzilla.mozilla.org/show_bug.cgi?id=1567230 for its implementation.

**Comment by mnoorenberghe** [comment]
This was implemented in Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1194529 but it's off-by-default since many users didn't know their OS credentials. You can try it out by setting `signon.management.page.os-auth.enabled` to `true` in about:config
