### ISSUE TITLE
Lockwise can wrongly be installed on Firefox versions older than 67

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-lockwise/lockwise-addon#290]
[Notes]:
- This seems to be a regression since we have verified that the add-on is not compatible with Firefox 66 and older in issue [#161](https://github.com/mozilla-lockwise/lockwise-addon/issues/161#issuecomment-491788570).
- If the Lockwise add-on was never installed on Firefox versions older than 67, the browser crashes after the first install attempt of the add-on. After the browser is restarted the Lockwise add-on works as expected and if it is removed and reinstalled the browser no longer crashes.
- Also since the add-on can be installed on Firefox versions older than 66 the users will encounter the old issue #161.

[Affected Versions]:
- Lockwise 2.2.2-alpha
- Firefox 66 and older

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66 version installed.
- Have a new clean profile.

[Steps to reproduce]:
1. Open the Firefox 66 version with the profile from prerequisites.
2. Navigate to "https://lockwise.firefox.com/" website.
3. Click the "Install for Firefox" button.
4. Observe the behavrior. 

[Expected results]:
- A doorhnager which informs the users that the add-on is not compatible with Firefox 66 is displayed.

[Actual results]:
- The add-on is installing then the browser crashes.

[Additional Notes]:
- Attached a screen recording of the issue:
![Lockwise on 66](https://user-images.githubusercontent.com/19226534/58622944-82771d00-82d5-11e9-989d-8415c1f2c86f.gif)

**Comment by devinreams** [comment]
Odd. I do see the `[strict_min_version](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings)` still set in the manifest template and after downloading and unzipping the xpi...

**Comment by 6a68** [comment]
This seems extremely weird to me.

One possible workaround: we can sniff the user agent on the lockwise website and either disable or show an "upgrade your firefox" button if the version is less than 67.

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean I'm able to reproduce on 66.0.5. Could you try a few older versions of firefox as well, and see if this is a regression or old, known behavior?

* after the initial install-crash on 66.0.5, I can restart, then go to about:addons and disable/enable or remove/"undo" without causing another crash.
* after the initial install-crash on 66.0.5, I can restart, go back to the lockwise website, and reinstall without a crash. When I install the addon for a second time (in a profile that already has the addon), I see the following in the browser console:

<img width="1223" alt="Screen Shot 2019-05-30 at 8 20 34 AM" src="https://user-images.githubusercontent.com/96396/58643296-d5d87380-82b3-11e9-9be5-47ba5cf401d0.png">

Here is the text from the console:

```
1559229571343	addons.webextension.<unknown>	WARN	Loading extension 'undefined': Reading manifest: Invalid extension permission: mozillaAddons
1559229571408	addons.xpi-utils	WARN	Add-on lockbox@mozilla.com is not compatible with application version.

1559229571474	addons.xpi-utils	WARN	Add-on lockbox@mozilla.com is not compatible with application version.
unregister is not a function ExtensionCommon.jsm:2319
    removeListener resource://gre/modules/ExtensionCommon.jsm:2319
    revoke resource://gre/modules/ExtensionCommon.jsm:2341
    close resource://gre/modules/ExtensionCommon.jsm:2346
    unload resource://gre/modules/ExtensionCommon.jsm:802
    unload resource://gre/modules/ExtensionParent.jsm:638
    unload resource://gre/modules/ExtensionParent.jsm:720
    shutdown resource://gre/modules/ExtensionParent.jsm:630
    shutdown resource://gre/modules/ExtensionParent.jsm:726
    shutdownExtension resource://gre/modules/ExtensionParent.jsm:821
    shutdown resource://gre/modules/Extension.jsm:2016
    InterpretGeneratorResume self-hosted:1255
    next self-hosted:1210
    shutdown resource://gre/modules/Extension.jsm:1260
    InterpretGeneratorResume self-hosted:1255
    next self-hosted:1210
    callBootstrapMethod resource://gre/modules/addons/XPIProvider.jsm:1637
    InterpretGeneratorResume self-hosted:1255
    next self-hosted:1210
    _shutdown resource://gre/modules/addons/XPIProvider.jsm:1757
    InterpretGeneratorResume self-hosted:1255
    next self-hosted:1210
1559229572520	addons.webextension.<unknown>	WARN	Loading extension 'undefined': Reading manifest: Invalid extension permission: mozillaAddons
```

**Comment by 6a68** [comment]
After the initial install-crash, if I uninstall the addon completely, then go back to the lockwise.firefox.com website and reinstall, there is not a crash, and I see some curious lines in the browser console:

<img width="1004" alt="Screen Shot 2019-05-30 at 8 31 02 AM" src="https://user-images.githubusercontent.com/96396/58644028-4633c480-82b5-11e9-8ef5-bf2d66933d79.png">

Why would it say "loading extension 'undefined'"? 🙀 

```
1559230080584	addons.webextension.<unknown>	WARN	Loading extension 'undefined': Reading manifest: Invalid extension permission: mozillaAddons
1559230080655	addons.xpi-utils	WARN	Add-on lockbox@mozilla.com is not compatible with application version.

1559230080724	addons.xpi-utils	WARN	Add-on lockbox@mozilla.com is not compatible with application version.
```

**Comment by linuxwolf** [comment]
This extension is signed using the quite new COSE keys.  I wonder if that's a factor here ...

**Comment by 6a68** [comment]
@linuxwolf maybe...I tried the install on 66.0.5, which afaik is the latest post-armagaddon version of 66 (but I'll check the ftp site to be sure)

**Comment by 6a68** [comment]
Actually, that's probably it. The fact that the mozillaAddons permission is stripped indicates that 66 does not recognize the key as a mozilla-privileged key

**Comment by linuxwolf** [comment]
> @linuxwolf maybe...I tried the install on 66.0.5, which afaik is the latest post-armagaddon version of 66 (but I'll check the ftp site to be sure)

I should have said COSE signing.  It's a difference in the signature format, which older versions of Firefox don't support.

**Comment by SoftVision-CosminMuntean** [comment]
@6a68 I have tested this issue on older Firefox versions, here are the results:
- Firefox 66.0.5 - The browser crashes after installing the add-on.
- Firefox 65.0.2, 64.0.2, 63.0.3 - The browser didn't crash after installing the add-on. The add-on works as expected.
- Firefox 62.0.3 and 61.0.2 - The browser didn't crash after installing the add-on, but the add-on doesn't work. The Lockwise doorhanger cannot be opened.
Also, an error is displayed in the browser console after installing the add-on. See[ this screenshot](https://drive.google.com/open?id=1zXlQ-bHABmVfm0kv4anL1nXbLhFicBni).

However, considering the fact that the browser doesn't crash on Firefox older than 66, I have tried to find a regression range, but the issue is not reproducible on Nightly 66 builds.

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean Thanks so much! Could you try to reproduce on current nightly? @marniepw said she had this happen on nightly 69 just a few days ago

**Comment by linuxwolf** [comment]
There should be a BMO for this shortly, let's move future discussion and testing there.

If the crashes are happening with the same logs as above, it does not appear there is anything that can be done in the extension itself.

**Comment by SoftVision-CosminMuntean** [comment]
@6a68  I just tested on latest Nightly 69.0a1 but the issue is not reproducible. The Lockwise add-on is successfully installed and the browser doesn't crash. However, I will do more investigation tomorrow and I will leave a comment if I find something.

Also, as you suggested I have logged the issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1555734

**Comment by pdehaan** [comment]
I was unable to repro on 68.0b5 (macOS), but I'll continue checking all browsers between 66.0.x and Nightly.

**Comment by pdehaan** [comment]
Got the crash on 66.0.4.
Here's the output from the Mozilla Crash Reporter:

```
AdapterDeviceID: 0x67ef
AdapterVendorID: 0x1002
Add-ons: lockbox%40mozilla.com:2.2.2-alpha,formautofill%40mozilla.org:1.0,screenshots%40mozilla.org:35.0.0,webcompat%40mozilla.org:3.0.2
BuildID: 20190504212614
ContentSandboxCapable: 1
ContentSandboxLevel: 3
CrashTime: 1559240564
DOMIPCEnabled: 1
EMCheckCompatibility: true
EventLoopNestingLevel: 1
FramePoisonBase: 9223372036600930304
FramePoisonSize: 4096
InstallTime: 1557162798
Notes: FP(D00-L1000-W00000000-T000) WR? WR- OMTP? OMTP+4 GL Layers? GL Context? GL Context+ GL Layers+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 1454461
StartupCrash: 0
StartupTime: 1559240534
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20190504212614","version":"66.0.4","vendor":"Mozilla","displayVersion":"66.0.4","platformVersion":"66.0.4","xpcomAbi":"x86_64-gcc3","updaterAvailable":true},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":32768,"virtualMaxMB":null,"cpu":{"count":12,"cores":6,"vendor":"GenuineIntel","family":6,"model":158,"stepping":10,"l2cacheKB":256,"l3cacheKB":12288,"speedMHz":2900,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Darwin","version":"18.6.0","locale":"en-CA"},"hdd":{"profile":{"model":null,"revision":null},"binary":{"model":null,"revision":null},"system":{"model":null,"revision":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","LowEndMachine":false,"adapters":[{"description":null,"vendorID":"0x1002","deviceID":"0x67ef","subsysID":null,"RAM":null,"driver":null,"driverVersion":null,"driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1080,"scale":1},{"screenWidth":1680,"screenHeight":1050,"scale":2},{"screenWidth":1920,"screenHeight":1080,"scale":1}],"features":{"compositor":"opengl","gpuProcess":{"status":"unused"},"wrQualified":{"status":"blocked"},"webrender":{"status":"opt-in"}}},"appleModelId":"MacBookPro15,1"},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US"],"availableLocales":["en-US"],"appLocales":["en-US"],"systemLocales":["en-CA"],"regionalPrefsLocales":["en-CA"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":true},"userPrefs":{"browser.search.widget.inNavBar":false,"browser.search.region":"CA"},"sandbox":{"effectiveContentProcessLevel":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":false,"defaultSearchEngine":"google-b-d","defaultSearchEngineData":{"name":"Google","loadPath":"jar:[app]/omni.ja!/google-b-d.xml","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-d&q="},"searchCohort":"nov17-2"},"profile":{"creationDate":18046,"firstUseDate":18046},"addons":{"activeAddons":{"formautofill@mozilla.org":{"version":"1.0","scope":1,"type":"extension","updateDay":17995,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17995},"screenshots@mozilla.org":{"version":"35.0.0","scope":1,"type":"extension","updateDay":17995,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17995},"webcompat@mozilla.org":{"version":"3.0.2","scope":1,"type":"extension","updateDay":17995,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17995},"lockbox@mozilla.com":{"version":"2.2.2-alpha","scope":1,"type":"extension","updateDay":18046,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take your passwords everywhere.","name":"Firefox Lockwise","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18046,"signedState":4}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"A theme with the operating system color scheme.","name":"Default","userDisabled":false,"appDisabled":false,"version":"","scope":1,"foreignInstall":false,"hasBinaryComponents":false,"installDay":0,"updateDay":0},"activePlugins":[],"activeGMPlugins":{"gmp-gmpopenh264":{"version":null,"userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":null,"userDisabled":false,"applyBackgroundUpdates":1}},"persona":"default-theme@mozilla.org"},"experiments":{"searchCohort":{"branch":"nov17-2"},"pref-rollout-block-autoplay-release-66-1535667":{"branch":"active","type":"normandy-prefrollout"}}}
ThreadIdNameMapping: 5:"Gecko_IOThread",6:"JS Watchdog",9:"JS Helper",10:"JS Helper",8:"JS Helper",7:"JS Helper",11:"JS Helper",12:"JS Helper",14:"JS Helper",13:"JS Helper",15:"Timer",16:"Socket Thread",18:"Cache2 I/O",19:"Cookie",22:"DOM Worker",21:"IPDL Background",32:"GMPThread",33:"Worker Launcher",34:"Compositor",35:"ImgDecoder #1",36:"ImageIO",38:"mozStorage #1",41:"mozStorage #2",53:"StyleThread#2",56:"StyleThread#5",55:"StyleThread#4",51:"StyleThread#0",54:"StyleThread#3",52:"StyleThread#1",50:"ImageBridgeChild",51:"ProcessHangMon",55:"Lazy Idle",55:"localStorage DB",54:"ImgDecoder #2",55:"HTML5 Parser",58:"DataStorage",59:"DNS Resolver #1",60:"URL Classifier",61:"Classifier Update",62:"Cache I/O",63:"DOM Worker",63:"mozStorage #3",64:"DNS Resolver #2",64:"DOM Worker",66:"mozStorage #4",67:"SSL Cert #1",68:"QuotaManager IO",69:"IndexedDB #1",73:"IndexedDB #4",73:"DNS Resolver #3",74:"SSL Cert #2",75:"SaveScripts",77:"SSL Cert #3",78:"SSL Cert #4",79:"DNS Resolver #4",80:"SubtleCrypto #1",82:"mozStorage #5",82:"mozStorage #6",83:"ImgDecoder #3",84:"ImgDecoder #4",76:"mozStorage #7",79:"StreamTrans #143",
Throttleable: 1
URL: https://lockwise.firefox.com/
UptimeTS: 30.22274396
Vendor: Mozilla
Version: 66.0.4
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.
```

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Lockwise add-on version from the Lockwise website and the add-on can no longer be installed from the website on versions lower than 67. 
The "Install for Firefox" button changes into an "Upgrade Firefox" button if the page is opened on Firefox versions lower than 67.
However, even if you have the Lockwsie 2.2.3-alpha xpi and you try to install it on Firefox 66.0.5 or lower, you get an incompatible message and it cannot be installed.
Considering this the users will not be able to install the add-on on versions lower than 67 and will not encounter the issues mentioned above.

Based on this we no longer consider this issue as a blocker for the Lockwise release.
