### ISSUE TITLE
Suport for saving credit card information

### ISSUE THREAD

**Issue by rcsilva83** [mozilla-lockwise/lockwise-addon#300]
Hello,

I'm a Mozilla fan and I'd like switch from my current password manager (Bitwarden) to Lockwise. However, in Bitwarden I store my credit card info too and I use it a lot... Do you plan to add this feature?

Regards,

Rodrigo

**Comment by linuxwolf** [comment]
Support for other types of data (e.g., credit cards) is something being evaluated.  We don't have a timeline or roadmap for when or if other data types would be supported.

**Comment by nickolasclarke** [comment]
Yes please! In addition I store ID data such as driver's license, Social security, passport, etc. Autofill wouldmbe great, but just securely storing it would be good enough for now.

**Comment by NobleUplift** [comment]
I wouldn't personally store my credit card numbers, but I would love to have support for other data types such as Security Questions or PINs.

**Comment by jplatte** [comment]
@linuxwolf Is there a higher-level issue for that than this one? I don't care much about storing credit card info, but the missing support for secondary information to keep alongside the password for a site is currently keeping me from switching fully from keepassxc. I use its comment field for all sorts of things, like security questions, or the registered email if the username is something else (so I can easily find all sites I've given my email to, should I switch providers again).

**Comment by mnoorenberghe** [comment]
> @linuxwolf Is there a higher-level issue for that than this one

https://bugzilla.mozilla.org/show_bug.cgi?id=1119558 covers what you want

**Comment by mnoorenberghe** [comment]
Work on credit card autofill in Firefox has resumed and will first target en-US users: See https://bugzilla.mozilla.org/show_bug.cgi?id=1527746 and https://wiki.mozilla.org/Firefox/Features/Form_Autofill
