### ISSUE TITLE
Allow adding website aliases

### ISSUE THREAD

**Issue by renkejr-pkwy** [mozilla-lockwise/lockwise-addon#303]
For example, I added an entry for https://dev.azure.com which uses the same credentials as https://www.microsoft.com.  I'd prefer to add the azure.com site as an alias to the microsoft.com entry instead of creating another entry.

**Comment by linuxwolf** [comment]
Support for additional fields is being evaluated, but we don't have a timeline or roadmap for that support yet.

**Comment by adam7** [comment]
I don't think this is the same feature as additional fields. A really common use case when signing up for a service is that I sign up with url A (https://signup.foo.com) and then I have to, or can, log in at url B (https://id.foo.com), C (https://login.foo.com) or D (https://anotherservice.foo.com). 
Right now I have to maintain separate logins for every one of those, despite the fact it's the same login and password for every one. I should just be able to tell lockwise that they are all using the same login just at different urls.

**Comment by WhiteApfel** [comment]
I see this solution: Add passwords for the domain. And use on subdomains. And an additional opportunity to add other aliases

**Comment by renkejr-pkwy** [comment]
@WhiteApfel That solution does not work since the two domains may not be the same, such as outlook.com and microsoft.com which both use the same account.

**Comment by WhiteApfel** [comment]
Therefore, I wrote about the ability to add aliases. And it would be nice if there were built-in aliases for some domains.

**Comment by mnoorenberghe** [comment]
Firefox does suggest passwords for subdomains now. For the case of separate domains we are tracking that in https://bugzilla.mozilla.org/show_bug.cgi?id=1120684
