### ISSUE TITLE
Support LoginInfo IDL changes

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockwise/lockwise-addon#309]
Bug [1148205](https://bugzilla.mozilla.org/show_bug.cgi?id=1148205) changes the LoginInfo IDL to replace `hostname` with `origin`, and to replace `formSubmitURL` with `formActionOrigin`.

For compatibility with all versions of Firefox in the addon, we should allow for these keys in the embedded `logins` API experiment.

**Comment by mnoorenberghe** [comment]
Sorry about breaking your tests, I didn't run them but did a quick manual test of the add-on. If it's easier to add some compatibility shims back into Firefox then that's fine with me. I was trying to avoid you having to handle multiple versions in the add-on.

**Comment by linuxwolf** [comment]
I think it's ok to account for the change in the add-on.
