### ISSUE TITLE
Unable to install add-on on Firefox desktop

### ISSUE THREAD

**Issue by bullfroggie** [mozilla-lockwise/lockwise-addon#312]
Firefox version I'm using is **67.0.1** (64-bit)
I was trying to install Firefox Lockwise add-on on my Firefox (Desktop version), and was unable to do so.  I went to the website and clicked on the "Install for Firefox" button.
I was presented with an error message saying that **the add-on couldn't be downloaded due to connection failure**. This problem has been occurring for 2 days now. I should also mention that I don't have any  internet connection issues. 

**Below is a screenshot of the error message I'm receiving**
![lockwiseErr](https://user-images.githubusercontent.com/36682210/59151363-1feaf300-8a32-11e9-822f-b60096832df1.PNG)

**Comment by A-Charvin** [comment]
Had the same issue, Downloaded the XPI file and manually installed it onto firefox via about:addons page.
The connection issue needs to be looked into though.

**Comment by Pantyboy** [comment]
I'm also having this problem.

I can't seem to download via the 'Addons' page as the Lockwise doesn't appear in the addons.

**Comment by aZa1905** [comment]
same thing here!

**Comment by mnoorenberghe** [comment]
The add-on is now retired as the functionality is built-in for Firefox 70+.
