### ISSUE TITLE
editable url

### ISSUE THREAD

**Issue by waclaw66** [mozilla-lockwise/lockwise-addon#314]
Hi.

Please enable edit of url. Many urls have been changed, e.g. from http to https or there was a subdomain change. I don't want to create new login records and delete the old once.

Thanks.

**Comment by BewilderedAgain** [comment]
I second this. At the moment the stored URL is just the root path to the site.  Working on a company site where there are different logins for different areas mean you have no way to select the username / password combination specific to that area.  Ideally lockwise should store the whole URL so this would be a workaround. As it stands it's really not fit for the purpose.

**Comment by mnoorenberghe** [comment]
Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1578063
