### ISSUE TITLE
"Upgrade Firefox": Can't install from Lockwise website

### ISSUE THREAD

**Issue by mitchellknight** [mozilla-lockwise/lockwise-addon#316]
I cannot install the Firefox Lockwise Addon from [the Lockwise website](https://lockwise.firefox.com/). I only see an ["Ugprade Firefox"](https://www.mozilla.org/en-US/firefox/download/thanks/) button.

The problem is I'm on the latest version of Firefox: 67.0.2 (64-bit). I do not see a work around or another way to install. Can someone provide a direct download link on the website for those of us experiencing this issue.

Additional details:

- I'm running Firefox 67.0.2 (64-bit) on macOS 10.13.6 ("High Sierra").
- I do have passwords saved and synced with a Firefox account.
- Extensions: Multi-Account Containers, Facebook Container, Authenticator, uBlock Origin, HTTPS Everywhere
- I do have a custom `user.js` in my profile with a bunch of privacy stuff: resistFingerprinting, disable telemetry, clear history on close, etc.

**Comment by SoftVision-CosminMuntean** [comment]
Hi @mitchellknight, thanks for your detailed report.

From what I understand you have the "privacy.resistFingerprinting" pref set to "true". This pref also change the "User Agent" of the browser and it is recognized as Firefox 60.0 version. You can see this in "about:support" page at the "User Agent" section.

The Lockwise add-on is not compatible with Firefox versions lower than 67. So when you navigate to the Lockwise website, it detects that your version of the browser is 60 and displays the "Upgrade Firefox" button.
As a workaround, you can switch the pref to "false" then you install the add-on. After the add-on is installed you can switch back the pref to "true". Or you can install the latest version of Lockwise from [Github](https://github.com/mozilla-lockwise/lockwise-addon/releases/).

**Comment by mitchellknight** [comment]
Thank you! I installed it on a different profile, found the `.xpi`, and then used the `.xpi` to install it on my main profile.

I still think it would be a good idea to update the Lockwise website with a small link to manually install near the main button even if Firefox > 67 isn't detected. It's not really a good UX practice to take control away from the end user.

Closing this issue for now.
