### ISSUE TITLE
dafuq? where are the docs?

### ISSUE THREAD

**Issue by systemcrash** [mozilla-lockwise/lockwise-addon#318]
Clicks docs link. https://mozilla-lockbox.github.io/lockbox-addon/ 

404. 

**FOUR ZERO FOUR!** 

Clicks docs folder on github. 
You can read this documentation online or by browsing the docs directory on GitHub.

"go to docs link!1! lol"

Please see the Firefox Lockwise website for more context.

Click. No context. 

Hmm, what's this tiny FAQ link?

FINALLY.  *some* information

**Comment by devinreams** [comment]
@systemcrash the URL is since the project was renamed to "lockwise" from "lockbox":
https://mozilla-lockwise.github.io/lockwise-addon/

I hope you find what you're looking for..
