### ISSUE TITLE
Allow editing "website address"

### ISSUE THREAD

**Issue by tonglil** [mozilla-lockwise/lockwise-addon#329]
Allow me to update the website address to `https` from `http`:

View:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/3250776/60548494-107c6400-9cd7-11e9-98d6-99db409a948c.png">

Edit:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3250776/60548501-16724500-9cd7-11e9-977c-15c8baa7cc02.png">

Can only change other fields or delete. Need to update. There is no duplicate functionality.

**Comment by Eagle3386** [comment]
Duplicate of #314.

**Comment by mnoorenberghe** [comment]
Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1578063

**Comment by hanyas** [comment]
How is this still a thing!

**Comment by Eagle3386** [comment]
Since this issue got closed & just right above your comment, there's a link to the corresponding Bugzilla entry, probably nobody from the officials will reply to you.
