### ISSUE TITLE
Question: where should issues on Lockwise embedded in FF69 be reported?

### ISSUE THREAD

**Issue by klint** [mozilla-lockwise/lockwise-addon#331]
I'm looking for the right place to report bugs after activating signon.management.page.enabled in about:logins page in FF69beta. 
Is it here or in bugzilla?
Thanks

**Comment by changecourse** [comment]
Hello @klint 

The best place to report bugs would be Bugzilla; this repo is for the add-on version of Lockwise.

https://bugzilla.mozilla.org/buglist.cgi?product=Toolkit&component=Password Manager 


Thanks!
