### ISSUE TITLE
Backup (Export & Import) option

### ISSUE THREAD

**Issue by maverick74** [mozilla-lockwise/lockwise-addon#332]
Would be great and very useful to have Export/Import as a backup option.

However, considering the (recent) visibility given to the Logins and Passwords on the main menu (where even the newbies can easily access  passwords) this may pose a security risk as anyone can - very fast - access the passwords of anothers' computer and export them...

**Comment by unixuser011** [comment]
It's been pointed out in another issue thread about this same isse that import and export is required under GDPR right to data portability. This can only be a good thing as it will increase it's standing and make more people willing to migrate from other popular password management tools such as LastPass and 1Password to LockWise

**Comment by maverick74** [comment]
Yes, now that you mention it I think I've read that already.

Still, I think it's important to solve #324 first

**Comment by unixuser011** [comment]
does #324 refer to against using a master password or pro-master password. Once would certainly be better than the other. Having an open password vault is bad for all the obvous reasons, but if using a master password, it [LockWise] shouldn't save it, because then all someone would need to do is open your vault, auto login and you've lost your password valut

But yea, solve #324 before anything else

**Comment by maverick74** [comment]
I think #324 it referes to using a password just when you try access lockwise page manager (at least I hope so).

The important is to block backups and the possibility to actually view the passwords. All else regarding UX should stay the same... That's what I hope for.

So, asking for a password only when a user tries to access lockwise page would do just fine

**Comment by unixuser011** [comment]
If there is going to be an export option (which could be an option if, for example, someone switched to LockWise, imported their password DB, and wanted to switch back because LockWise didn't offer a feature they wanted) lets hope the password DB is not human readable (which kinda defeats the purpose of exporting to CSV)

I have no problem with asking for a password to login to said password vault, helps provide an extra layer of security I suppose

**Comment by truseer** [comment]
Duplicate of #133

**Comment by klausenbusk** [comment]
> Duplicate of #133

There is some overlap, but the goal is different:

#133: import from 3rd party password manager.

#332: import/export for backup purposes.

**Comment by eggsgent** [comment]
Import and export feature request should be split, how about making this one only about export (backup)?

**Comment by maverick74** [comment]
Since "Import" is already available ( it's just missing an "import from file" option), I'm OK with it being turned into export-only feature request.

But, please, post a link here to the new "import feature request"

**Comment by cata0309** [comment]
I can't find this 'import' feature that you are talking about

**Comment by maverick74** [comment]
@cata0309 
Open lockwise - top right corner (on the username, if I remember correctly) - import from other browsers

**Comment by changecourse** [comment]
One point of clarification, @cata0309 

Importing of saved logins from another browser is available in the upcoming release of Lockwise Desktop, the login manager native to Firefox (as opposed to this web extension)

You can access this functionality now via Firefox Nightly or Beta, and on our release candidate for 70 via "Logins & Passwords" as @maverick74 has stated :)

**Comment by maverick74** [comment]
Still, it does not allow import from a file. 

But, then again, there is no way to export logins anyway, so it wouldn't make any sense.

(except manually from the profile folder)

**Comment by tmikaeld** [comment]
Import from CSV or similar is sorely needed, or you'll never convert users that use other password managers. Even with only +20 passwords, it's a tedious work to move them over manually which people will simply not do.

**Comment by changecourse** [comment]
@tmikaeld agreed, and it's certainly on our road map for the midterm future :)

**Comment by truseer** [comment]
That's why I, personally, haven't fully converted.

**Comment by EazyCheeze1978** [comment]
Just discovered LockWise as built-in to Firefox, and apparently it's been there for a while; great concept for streamlining password managing to the browser instead of using a separate manager. I'm currently doing that, actually. I think it'd be great if we could import a (highly insecure, I'm aware) .json file, as my current manager supports export using that format. Otherwise that's 100+ logins I need to recreate manually, and I'm not liking the time/manpower required for that :)

**Comment by changecourse** [comment]
Thanks for the suggestion @EazyCheeze1978! That does sound laborious, importing manually :) 

Does your current manager also support for other file formats, such as .csv?

**Comment by EazyCheeze1978** [comment]
CSV and TXT, yes. :) And you're welcome, and thanks! :)

**Comment by elken** [comment]
LastPass, 1Password and Bitwarden should all support csv ,json and txt exports with similar schemas. 

Imprint/Export is the only blocker stopping me from using and I'm sure many others are in the same boat. If it's not high priority on the roadmap I can maybe attempt a PR at the weekend.

**Comment by changecourse** [comment]
Thank you for your willingness to help, @elken! It is worth mentioning that at this time, however, that the work on the add-on has been paused as we've now brought this functionality native into the browser (it's a core part of Firefox 70), so any work to accelerate progress on import/export of text files would likely need to start with Firefox instead. 

In the future, as we look to bring the web extension to other browsers, it'd certainly be valuable to have it built in this repo as well, but that's a longer term vision.

**Comment by andreicristianpetcu** [comment]
Untill this gets fixed, you can use https://github.com/louisabraham/ffpass

**Comment by kjaerlige** [comment]
I wanted to migrate back to Firefox from KeePass which supports export as a "Mozilla Bookmarks HTML", but I wasn't able to import such HTML into LockWise. Would really appreciate to be able to do that

**Comment by alexandrestein** [comment]
Where can we track the status of export inside Firefox.
As @changecourse mentioned it's now part of Firefox.

I trued [ffpass](https://github.com/louisabraham/ffpass) as mentioned by @andreicristianpetcu and [ff-password-exporter](https://github.com/kspearrin/ff-password-exporter) but they can't make the job.

There is an issue decoding the logins. `DER can't be decoded`

**Comment by changecourse** [comment]
You can track the bug for Firefox [here](https://bugzilla.mozilla.org/show_bug.cgi?id=249801)

Also, fwiw, there are some 3rd party options for exporting, for the time being, as discussed in the bug.

**Comment by alexandrestein** [comment]
Thank you @changecourse. I'm now following the right issue. :smiley: 

As mentioned I tried 2 different 3rd party tools but they did not do the job.

I even tried to use Chrome to import the password from Firefox but even Chrome does not work.

I hope to see this done shortly.
Thanks.

**Comment by kapn1966** [comment]
I am dumbfounded that this is not solved already.

**Comment by towerpark** [comment]
[ffpass](https://github.com/louisabraham/ffpass/issues/49) is not working from probably FF 72.

**Comment by mnoorenberghe** [comment]
https://github.com/lclevy/firepwd/ is working

**Comment by Sebb767** [comment]
As someone who wants to migrate away from Chrome and has a lot of saved passwords, this is an absolute dealbreaker. Import from other browsers doesn't work on Linux, either, so that route won't work. And recommending to siphon my passwords through third party tools sounds horrible security-wise (no offence to firepwd or ffpass), not to mention that they're obviously not supported.

_Please_ implement this.

**Comment by mnoorenberghe** [comment]
@Sebb767 It sounds like you actually want https://bugzilla.mozilla.org/show_bug.cgi?id=1513718 which I have offered to mentor someone on years ago. If you know JS you could take a look.

**Comment by Sebb767** [comment]
@mnoorenberghe Thanks for the link! A generic importer seems more useful, but that would solve my issue as well. If Obayagbona doesn't implement this I might give it a shot.

**Comment by mnoorenberghe** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1641777 will support import from Firefox's own CSV export and https://bugzilla.mozilla.org/show_bug.cgi?id=1303176 will support importing from the CSV files produced by other password managers.

**Comment by andreicristianpetcu** [comment]
Import also landed in Nightly. It currently supports Firefox, Chrome and Bitwarden.
![image](https://user-images.githubusercontent.com/922368/86542172-f2fe5d80-bf1b-11ea-8fc9-7fba418c3e64.png)

The mapping works like this:
```

const FIELD_TO_CSV_COLUMNS = {
  origin: ["url", "login_uri"],
  username: ["username", "login_username"],
  password: ["password", "login_password"],
  httpRealm: ["httpRealm"],
  formActionOrigin: ["formActionOrigin"],
  guid: ["guid"],
  timeCreated: ["timeCreated"],
  timeLastUsed: ["timeLastUsed"],
  timePasswordChanged: ["timePasswordChanged"],
};
```
https://searchfox.org/mozilla-central/source/toolkit/components/passwordmgr/LoginCSVImport.jsm#33-43

**Comment by andreicristianpetcu** [comment]
Import form CSV has landed in Nightly and unless we find some critical bug, we intend to ship it in v86 :crossed_fingers: 
Please test.

**Comment by innovation-plantation** [comment]
Tested 88.0.1 (64 bits) on Windows10 and found a problem: It can't read back its own exported data, complains about headers on the CSV. I tried messing with quoting or unquoting them, making sure capitalization matches the names asked for in the error message, nothing works. 

Here's what happened. I have a somewhat corrupted Windows user profile and decided to make an entirely new account and move everything there. Backed up by exporting using CSV, went to the new profile, and attempted to import. It won't "eat its own dogfood" so to speak, and this is a definite problem. Importing an exported file should be a most basic step of testing the code.

**Comment by cadeyrn** [comment]
@innovation-plantation 

> Tested 88.0.1 (64 bits) on Windows10 and found a problem

This is the bugtracker for Firefox:
https://bugzilla.mozilla.org/

This issues tracker is for the no longer maintained browser extension, not for the integration in Firefox.

**Comment by andreicristianpetcu** [comment]
@innovation-plantation can you please share the exported file? please anonimize the data.

**Comment by innovation-plantation** [comment]
No, I can't. It's credentials in cleartext

**Comment by andreicristianpetcu** [comment]
Remove as many rows as possible as long as the bug reproduces and anonimize the rest. Put 'test1/test2/test3' for passwords test1@example.com for url. Anonimize it.
