### ISSUE TITLE
Cannot add or sync multiple passwords for one website

### ISSUE THREAD

**Issue by agi90** [mozilla-lockwise/lockwise-addon#335]
I experienced many variations of this bug, but mainly this STR seems reliable:

- Create password for account on website (e.g. site: amazon.com, user: agi@sferro.dev)
- Sync with other device
- Verify username/password is synched (pass)
- Add new password for same website with empty username (e.g. with the Nightly feature "generate password"), now you have this:
```
Site: amazon.com
User: agi@sferro.dev pass: abc
User  ""             pass: abd
```
- Try to edit the new entry to match the previous username, like this:
```
Site: amazon.com
User: agi@sferro.dev pass: abc
User  agi@sferro.dev pass: abd
```

- Notice this update doesn't go through (fail)

Removing the first entry will make the edit (and sync) work.

Similarly, when another password is added for a username that already exist, that user/pass combination will not be synched until you remove the old one.

**Comment by mnoorenberghe** [comment]
This is a requirement of the sync and storage layer that we are unlikely to change anytime soon.
