### ISSUE TITLE
Search by Password [Feature request]

### ISSUE THREAD

**Issue by seiya-git** [mozilla-lockwise/lockwise-addon#341]
Hello. Please, can you add option search by password not only by login, old password manager can do both searches

**Comment by vanessa-techno** [comment]
“”

**Comment by mnoorenberghe** [comment]
Firefox 70 has this ability as long as you don't have a Master Password enabled.

**Comment by seiya-git** [comment]
@mnoorenberghe, yeah but only strick much

**Comment by mnoorenberghe** [comment]
It does a substring match
