### ISSUE TITLE
Lockwise should report which device it is installed on in the Firefox Account Devices & apps list

### ISSUE THREAD

**Issue by eggsgent** [mozilla-lockwise/lockwise-addon#343]
Lockwise should report which device it is installed on in the Firefox Account Devices & apps list

1. Go to https://accounts.firefox.com/settings/clients
2. Press the Devices & apps to see the list of entries

Actual result: Firefox Lockwise either has a mobile phone or Lockwise icon while Firefox with sync enabled reports Windows account name or Android model + approximate location
Currently it is hard to know which devices those installs are residing on.

Expected result: Firefox Lockwise should also show Windows account name or Android model + approximate location

![Lockwise](https://user-images.githubusercontent.com/7951056/64911566-aeeb6380-d723-11e9-84a2-f555dae98b62.PNG)

**Comment by changecourse** [comment]
Hello @eggsgent, thanks for contributing this issue! 

The FxA Device & Apps list is associated with the FxA repo... and this very issue is logged over there: https://github.com/mozilla/fxa/issues/2505 

Feel free to contribute to that conversation based on your idea above!

**Comment by eggsgent** [comment]
Thanks @changecourse, shall I close this one as dupe?

Btw, as fxa is not part of the many Lockwise repos, it's hard for users / testers to find the correct place to report bugs, feature requests etc. There's the Mozilla Bugzilla as well, not sure how that bugtracker fits with the new modus operandi at Mozilla?
