### ISSUE TITLE
Lockwise just overwrote my password with *******

### ISSUE THREAD

**Issue by Yoric** [mozilla-lockwise/lockwise-addon#344]
No, this not a joke.

My bank uses a visual password input, probably in the hope of defeating keyloggers. I need to click on randomly-positioned buttons holding the possible digits for my password and the page literally displays `*********`.

Lockwise just overwrote my password with this literal `*********`. Took me some time to realize that this was not Lockwise hiding my password but the actual characters in the password.

**Comment by mnoorenberghe** [comment]
This doesn't sound related to the add-on which is only a management UI. Please file at https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Password%20Manager:%20Site%20Compatibility
