### ISSUE TITLE
Support for custom sync server?

### ISSUE THREAD

**Issue by acidicX** [mozilla-lockwise/lockwise-addon#346]
Hi there,

I've found nothing in the docs, but does the addon also support a custom sync server (`services.sync.clusterURL` / `identity.sync.tokenserver.uri`) ?

**Comment by mnoorenberghe** [comment]
The add-on uses the existing sync and storage that logins on Firefox have used for years so anything they support will also be supported by the add-on since the add-on is mostly a new management UI layer.

**Comment by godfuture** [comment]
In Firefox desktop I have specified a custom sync uri to my firefox sync server (still using a Firefox account for auth). I tried it once on Android and saw all my passwords. How would the Android app know of my custom sync server, I haven't specified it. 

I have as well my problems in understanding the whole setup of Firefox Lockwise in combinaton custom sync servers. Where does my data go? How do the applications have access to it?

Thanks a lot, really interested.
