### ISSUE TITLE
Support for firefox developer edition. FF70

### ISSUE THREAD

**Issue by harpreetsb** [mozilla-lockwise/lockwise-addon#347]
I am using Firefox developer edition as my default browser & for development purposes.
Please update lockwise to support Firefox 70 as well

**Comment by cadeyrn** [comment]
There is no need for the Lockwise add-on in Firefox 70 and higher - it's integrated in Firefox. Just open the login manager in Firefox 70 and you will see the Lockwise interface.

**Comment by harpreetsb** [comment]
Does this also mean that new logins will sync with android lockwise application?

**Comment by harpreetsb** [comment]
I really miss the interactive button for toolbar.

**Comment by mnoorenberghe** [comment]
> Does this also mean that new logins will sync with android lockwise application?

Yes, Firefox sync has synced logins from Firefox for years.
