### ISSUE TITLE
"Unable to sync logins" in Nightly 71

### ISSUE THREAD

**Issue by krzyk** [mozilla-lockwise/lockwise-addon#348]
Since 1 or 2 days I have issue that my Firefox disconnected from sync (not sure why) and now when I connect to sync I don't have my passwords synced at all.
I have only a single password for for firefox sync and that's all.

And since yesterday in Logins and passwords I see a yellow bar at the top with a "Unable to sync logins", but when I click "Reconnect" button (that is in this bar) the window closes, when I go again to passwords I still don't see my passwords and again the "Unable to sync logins".

Is there a way to debug this somehow? Could I see what happens in the background when I click that button to see what is blocking Lockwise?

**Comment by mnoorenberghe** [comment]
Hello, please file a bug at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Sync
