### ISSUE TITLE
Can't delete stored login

### ISSUE THREAD

**Issue by Eagle3386** [mozilla-lockwise/lockwise-addon#349]
I've got (for whatever reason) 2 logins for a website, e. g. `signin.mozilla.com`.
One was created back in the days of 2015 and has `user1234` as its username.
The other one got created last year and has `USER1234` as its username.
Both share the _same_ URL (including HTTPS prefix) and password.

Now, clicking <kbd>Delete</kbd> in the upper-right corner of `moz-extension://0610dcf4-62fc-4118-a4b6-0f30ad0d8ba1/list/manage.html?filter=&entryPoint=mainmenu` in Firefox Nightly 71.0a1 on Windows 10 for any of both entries and confirming the deletion results in no entry being deleted.

Reproducing the same steps via Firefox Lockwise on my Android smartphone, I got the entry deleted. However, I can click/tap <kbd>Sync</kbd> as much as I can on both devices (desktop & mobile) - neither will the deleted entry be synced to desktop nor will its remaining entry be ported back to mobile.

**Comment by mnoorenberghe** [comment]
The extension is no longer supported in Nightly 70+. Please uninstall the extension and use the built-in experience which hopefully doesn't have this problem.

**Comment by Eagle3386** [comment]
While both, your comment and the extension's removal upon Nightly 70's installation could've been way friendlier and more user-friendly, I hereby confirm that uninstalling the extension _and_ restarting Nightly solved the problem.

**Comment by cadeyrn** [comment]
> While both, your comment and the extension's removal upon Nightly 70's installation could've been way friendlier

i can't find anything unfriendly in the comment at all. Quite the opposite. 🤔

**Comment by Eagle3386** [comment]
I disagree with both of your statements. But feel free to keep your perspective.
