### ISSUE TITLE
When deleting the login pre-fill, the popup to unlock lockwise disappear

### ISSUE THREAD

**Issue by jicheu** [mozilla-lockwise/lockwise-addon#351]
* Go to a page such as paypal.com
* login prefilled
* erase prefilled
* lockwise popup does not appear

**Comment by mnoorenberghe** [comment]
The Lockwise add-on didn't provide any in-content autocomplete. Are you talking about the functionality built into Firefox? If so, please file a bug [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Password%20Manager:%20Site%20Compatibility)
