### ISSUE TITLE
Feature request: Delete multiple logins at once

### ISSUE THREAD

**Issue by jsnjack** [mozilla-lockwise/lockwise-addon#353]
I have many unused logins stored in Lockwise. At the moment it is possible to delete only one login at once (by selecting it in the list, clicking Delete button and clicking on the confirmation popup). Would be nice to be able to select multiple logins using Shift+click or/and Ctrl+click on the list view and delete all selected logins at once.

**Comment by yehia2amer** [comment]
I do have the same problem, I am trying to remove all my logins from firefox & Lockwise.

The only way to do that now is **Installing old Firefox version (Pre 70)**
Then Go to Privacy & Security" ---> "Saved Logins" ---> "Delete all" !

**Comment by cadeyrn** [comment]
> The only way to do that now is **Installing old Firefox version (Pre 70)**

No, it's not the only way. You can open chrome://passwordmgr/content/passwordManager.xul - it's still there in Firefox 70 (and current Firefox 72 Nightly). I guess it will be removed at some point in the future but it should be okay as a workaround - and it's definitively better than using an dold browser with security vulnerabilities. ;-)

**Comment by jsnjack** [comment]
thanks @cadeyrn ! Exactly what I was looking for!

**Comment by apvanzanten** [comment]
This is still an issue, and it seems that the method described by @cadeyrn no longer works in Firefox 73. Does anybody know of any other option?

**Comment by cadeyrn** [comment]
It's chrome://passwordmgr/content/passwordManager.xhtml instead of chrome://passwordmgr/content/passwordManager.xul since Firefox 73.

**Comment by apvanzanten** [comment]
@cadeyrn that works! Thanks :)

**Comment by mnoorenberghe** [comment]
We are working on this in https://bugzilla.mozilla.org/show_bug.cgi?id=1208194
