### ISSUE TITLE
Password autofill is disabled everytime I restart firefox

### ISSUE THREAD

**Issue by happychameleon** [mozilla-lockwise/lockwise-addon#355]
Whenever I restart firefox the setting "Ask to save logins and passwords for websites" in the preferences for lockwise is disabled, which means the "Autofill logins and passwords" option gets disabled. I can renable it and "Autofill logins and passwords" works like normal but as soon as I restart firefox it is disabled again.

**Comment by mnoorenberghe** [comment]
Hello, what extensions do you have installed? Extensions are able to disable this setting themselves so likely one of yours is doing that.

**Comment by happychameleon** [comment]
Yep your right, I installed Roboform which it seems disables the setting, thanks for the help
