### ISSUE TITLE
Long Passwords break management UI

### ISSUE THREAD

**Issue by 0az** [mozilla-lockwise/lockwise-addon#356]
When a long password is saved, the login item container extends to contain the password, pushing the "edit" button off-screen.

IMHO, the password should get truncated if it would go off-screen.

**Comment by mnoorenberghe** [comment]
Hello, are you using the built-in Fx70+ experience or the deprecated extension?

**Comment by 0az** [comment]
CNR, closing issue. Did a recent update fix this? I swear, it existed last week at some point with a version no greater than 71.0b8, with built-in experience, on macOS. 

Ah well. It's working perfectly fine now, and that's what matters. 🎉
