### ISSUE TITLE
Percent character in password causing troubles and strange base64 password encoding

### ISSUE THREAD

**Issue by pprivately** [mozilla-lockwise/lockwise-addon#361]
There is strange problem happening on Mozilla Add-on on Firefox Browser 70.0.1 (64bit) (at least) on Windows 10 1903.
When you try to login to some site with password like MyPassword_123% (note percent at the end of the password string) Add-On will offer to remember username and password. However it will change password on the fly to base64 encoded string and it will remember it like that.
That will later not work properly of course, because if you try to login next time with suggested (recently remembered) password it will autofill base64 string. Login will fail.
Could you take a look on that? Seems to be strange bug :-) Do not you like % in passwords? ;-)

**Comment by mnoorenberghe** [comment]
Is this only happening on a specific site? It's possible the website is the one using base64. Please file a bug [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Password%20Manager:%20Site%20Compatibility) as this issue is unrelated to the addon.

**Comment by pprivately** [comment]
It is a pity that you even did not try to replicate and it is easy like hell.

**Comment by mnoorenberghe** [comment]
I can't reproduce this issue… it's a site-specific problem… the site is probably does client-side hashing. This sounds like [bug 1600397](https://bugzilla.mozilla.org/show_bug.cgi?id=1600397) and has nothing to do with this Github Repo.

**Comment by pprivately** [comment]
Apology for insult - it really is site specific. I am not opening any issue.
