### ISSUE TITLE
Edit doesn't update last modified

### ISSUE THREAD

**Issue by dehghani-mehdi** [mozilla-lockwise/lockwise-addon#364]
Hi,

Steps:
1. Open up `about:logins`
2. Select any saved logins
3. Click on `Edit` button
4. Change the username
5. Click on `Save Changes` button

Expected: `Last modified` should b updated
Actual: But doesn't.

**Comment by mnoorenberghe** [comment]
As of now this is intentional if the password wasn't changed.

**Comment by dehghani-mehdi** [comment]
I think that's wrong behavior. `Username` is important same as `Password`.

**Comment by mnoorenberghe** [comment]
Unfortunately we rely on it being specific to the password in order to show more accurate breach warnings. We perhaps could have two separate timestamps but I don't think that will happen anytime soon.
