### ISSUE TITLE
Feature request: Password expiration.

### ISSUE THREAD

**Issue by rs410ga** [mozilla-lockwise/lockwise-addon#365]

**Comment by Vixavius** [comment]
Password expiration by time is strongly recommended against in modern practices, but this is mostly from the context of not being managed by a password manager.

Recommending changing the master password infrequently with a sufficiently strong and unique/different password may be more valuable than expiring individual passwords, as well as integration with tools that detect when a password/hash has been compromised for a particular service.

**Comment by mnoorenberghe** [comment]
Since the original report had little details I will close this.
