### ISSUE TITLE
Ability to generate password on `create new` view

### ISSUE THREAD

**Issue by a2xchip** [mozilla-lockwise/lockwise-addon#368]
Hi! There is option to generate password in registration forms, but this feature is missing when new account is added manually using `Create new` form.

 
![Screenshot from 2019-12-18 20-30-07](https://user-images.githubusercontent.com/6627334/71112941-435adb80-21d5-11ea-98f2-d6a73725d830.png)

**Comment by mnoorenberghe** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1606578
