### ISSUE TITLE
Feature Request: Generate passwords on demand

### ISSUE THREAD

**Issue by rsertelon** [mozilla-lockwise/lockwise-addon#371]
Having a way to generate secured passwords on demand would be great.
I could use it to generate passwords that won't necessarily be used on the web.

Also, choosing the character set involved in the password creation would be nice too, since some websites don't accept currently generated passwords.

**Comment by joedf** [comment]
What I'm surprised about, is that the passwords are only Alphanumeric!? smaller entropy! I know that some "legacy" style websites don't support symbols... I am imagine the choice for browsers is always convenience over security? 🤔

**Comment by nzain** [comment]
Many sites require at least one special character. Using a password manager + generated passwords means the user will never (99.9%) try to remember it. Instead, the user is interested in security - why reduce to alphanumeric?

I've migrated from LastPass and only one of my sites does not allow symbols, while many others explicitly do. This I needed to generate passwords elsewhere :-(

The OP might want to edit the title to include "add option for symbols" or similar.

**Comment by mnoorenberghe** [comment]
This is the issue tracker for the Lockwise add-on that is no longer supported as the functionality is built into Firefox. Issues with Firefox should be filed at https://bugzilla.mozilla.org

**Comment by nzain** [comment]
thanks for clarifying @mnoorenberghe . A note on the readme.md would help others with similar intent :)

**Comment by nzain** [comment]
Actually, mozilla stil refers to this github project when reporting bugs (look for lockwise): 
https://bugzilla.mozilla.org/enter_bug.cgi#h=otherProducts%7C

**Comment by kbrosnan** [comment]
The Lockwise bugzilla component exists for the mobile products. https://github.com/mozilla-lockwise/lockwise-android/ and https://github.com/mozilla-lockwise/lockwise-ios/

Issues with desktop Firefox should be reported to [Toolkit::Password Manager](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Password%20Manager) according to @mnoorenberghe

**Comment by nzain** [comment]
@kbrosnan moved my related bugzilla report into the right spot (toolkit + password manager) - thanks for that. [Lockwise generates alphanumeric passwords only](https://bugzilla.mozilla.org/show_bug.cgi?id=1620820)

**Comment by joedf** [comment]
Thanks everyone! 🥳
