### ISSUE TITLE
Passwords can be seen from console, without asking master password

### ISSUE THREAD

**Issue by akkyjumbade** [mozilla-lockwise/lockwise-addon#373]
While for every credentials asks for master password to reveal/ copy, there is a chance other users might get password without the master password.
by referencing the password input element in console and getting its value by property.
Here what i did

* Selected element from inspector
![image](https://user-images.githubusercontent.com/12668753/71657570-7de07e80-2d66-11ea-8432-1c4ae3bf4890.png)
* Go to console and get the value by the reference of ```$0.value```
* You will see the password

![Password reveals by passing in console by dom references](https://user-images.githubusercontent.com/12668753/71657515-31953e80-2d66-11ea-91a9-fa4ad3799619.jpg)

Passwords can be seen from console, without asking master password.

**Comment by mnoorenberghe** [comment]
> Passwords can be seen from console, without asking master password.

This is only possible if the master password was already unlocked. We are addressing this in https://bugzilla.mozilla.org/show_bug.cgi?id=1584126
