### ISSUE TITLE
Feature Request: Import from KeePass

### ISSUE THREAD

**Issue by joaoeudes7** [mozilla-lockwise/lockwise-addon#374]
Lockbox is a great tool, but don't forget the good old KeePass which is a reference in this password security issue, so it would be interesting to make it easier to migrate to Lockbox.

**Comment by mnoorenberghe** [comment]
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1303176

**Comment by joaoeudes7** [comment]
System of 1Password is equals to KeePass?

**Comment by mnoorenberghe** [comment]
The summary is "Bug 1303176 - Import passwords from popular password managers", it's not specific to 1Password and it even mentions the KeePass export format in [comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1303176#c3).

**Comment by andreicristianpetcu** [comment]
Import form CSV has landed in Nightly and unless we find some critical bug, we intend to ship it in v86 :crossed_fingers: 
Please test.
