### ISSUE TITLE
Default avatar as Background

### ISSUE THREAD

**Issue by GRcwolf** [mozilla-lockwise/lockwise-addon#375]
The default profile image/avatar on `about:login` is displayed as background even if the user has set an own avatar. This looks a bit strange if this avatar has a transparent background. Like in this example:

![Screenshot](https://user-images.githubusercontent.com/39116095/73015350-250f7d80-3e1c-11ea-86a6-07b8d20711b6.png)

**Comment by mnoorenberghe** [comment]
about:logins isn't used in the extension so you must be talking about the built-in Firefox experience. You can file a bug at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=about:logins (with your GitHub account)

**Comment by GRcwolf** [comment]
Thanks for the Feedback.
