### ISSUE TITLE
Feature Request: Generate a list of your passwords and additional information

### ISSUE THREAD

**Issue by LEx66** [mozilla-lockwise/lockwise-addon#377]
I would like to have a Feature, which gives you a list of your passwords in such a format.

1 www.example.net	Example@Example.net     ExamplePassword 
2 www.example.net	(no user)                           ExamplePassword 
3 www.example.net	ExampleUser                     ExamplePassword

**Comment by mnoorenberghe** [comment]
We'll implement this in https://bugzilla.mozilla.org/show_bug.cgi?id=249801
