### ISSUE TITLE
I can't see all my passwords

### ISSUE THREAD

**Issue by Yoric** [mozilla-lockwise/lockwise-addon#380]
I have encountered the same issue with several websites. Not entirely sure how to reproduce it yet, but the result is that there are passwords that can be auto-completed but that do not show up in Lockwise.

Steps to reproduce (I think):

- create an account on a website that requests your e-mail and your password separately;
- attempt to find the login in lockwise;
- can't find it.

**Comment by Yoric** [comment]
Deactivating lockwise lets me find the login in the default "saved logins" viewer, so it's probably a bug in Lockwise.

**Comment by mnoorenberghe** [comment]
Once we uninstalled the extension (since it's no longer supported) and reset `signon.management.overrideURI` the problem was solved.
