### ISSUE TITLE
[bug-report] Password from battle.net is saved as dot characters.

### ISSUE THREAD

**Issue by pfinnegane** [mozilla-lockwise/lockwise-addon#383]
When creating or updating a password on https://battle.net, passwords that are saved to Lockwise show as dot characters that look like periods as opposed to the actual password. This happens every time.

**Comment by mnoorenberghe** [comment]
Thanks. That's filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1277172 and will be fixed on Firefox Nightly in the next few weeks.

**Comment by mnoorenberghe** [comment]
@pfinnegane We should no longer save the period characters on this site in Firefox Nightly as the bug above is fixed. I'm not sure what the behaviour is now though.
