### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by oliverjanik** [mozilla-lockwise/lockwise-addon#385]
Passwords are extremely important in today's digital world. People choosing to rely on Lockwise long term need to understand Mozilla's commitment here. 

I really want to like Lockwise, but current rate of development has slowed down dramatically. Important features like (export, import) are missing.

Password management is all or nothing, no one wants to maintain passwords in multiple password managers.

I love Lockwise integration with FF and I love the Lockwise Android app, but can we get some affirmation of commitment from Mozilla?

My fear is that one day, this project gets shut down and people without ability to export their passwords will loose access to a lot of important accounts.

Can we get a statement from the leadership on this project?

**Comment by mnoorenberghe** [comment]
This repository is for the experiment add-on from 2018 and should be archived. The functionality was integrated into Firefox in 2019 so development happens there, not here. There has been a lot of major improvements and you will see more announced on Tuesday, such as password generation working on many more sites along with 3 other major improvements. 

Firefox has had a built-in password manager from the beginning and every browser has one so it's very unlikely that the password manager would be removed from Firefox. Import from other browsers has existed for years and we added Chrome on macOS last year. We will implement import from CSV shortly.

Follow development at https://wiki.mozilla.org/Toolkit:Password_Manager which is the backend for Firefox Desktop and Firefox for Android.
