### ISSUE TITLE
Feature request: Linking logins

### ISSUE THREAD

**Issue by mkielg11** [mozilla-lockwise/lockwise-addon#387]
This might be a dublicate, but I failed to find it anywhere else.

I have multiple sites, where the login uses the same active directory, or where the login is linked with other pages in similar way, such that username and password always are the same. This also means, that if it is changed on one page, it is changed on the other sites.
In the same use case, I also have to change the password with some interval, and therefore it is a pain, that the password is not synced between the sites.

Therefore, a feature enabling binding/linking logins across pages would be much appreciated. 
I understand that it may look like it promotes reusing passwords, but that is not the use case - and with the linking I propose, this would not work when changing the password (because you would then not be able to login on the other pages, as the previous password would not be remembered anymore).

**Comment by mnoorenberghe** [comment]
Thanks. We are tracking this in https://bugzilla.mozilla.org/show_bug.cgi?id=1120684
