### ISSUE TITLE
Showing and copying passwords doesn't work

### ISSUE THREAD

**Issue by krzyk** [mozilla-lockwise/lockwise-addon#390]
Since few latest Firefox Nightly releases (maybe longer, I tried last 3 I think) I am not able to show (by clicking the :eye: ) the password or copy it from the Lockwise Logins&Passwords.

It is very frustrating, because to be able to retrieve the autogenerated password I need to use android app and copy it manually to the PC.

My version is: 78.0a1 (2020-05-12) (64-bit)
OS: Linux

**Comment by mnoorenberghe** [comment]
Should be fixed in the next day or so: https://bugzilla.mozilla.org/show_bug.cgi?id=1636820

**Comment by mnoorenberghe** [comment]
You can install an older Nightly in the meantime.
