### ISSUE TITLE
Lockwise doesn't recognize Paypal login screen

### ISSUE THREAD

**Issue by osmgit** [mozilla-lockwise/lockwise-addon#391]
**What did you do? (steps to reproduce)**
1. Go to Paypal login screen: https://www.paypal.com/au/signin
2. Try to use Lockwise to sign in.

**What happened? (actual results)**
Lockwise does not appear on the first screen when logging into Paypal where you type your email / phone number. Lockwise only appears on the second password screen once you manually type your phone number / email.

**What should have happened? (expected results)**
Lockwise should recognize the first Paypal login screen.

**Comment by mnoorenberghe** [comment]
Thanks. We are tracking this problem in https://bugzilla.mozilla.org/show_bug.cgi?id=348941
