### ISSUE TITLE
Feature request: Firefox container aware accounts

### ISSUE THREAD

**Issue by Anthonyntilelli** [mozilla-lockwise/lockwise-addon#392]
I make use of firefox containers to manage logins and have multiple accounts for some sites.  It would be nice to group the account based on the container and for certain accounts to be only available when in that container. 

This will help with organizing passwords and prevent accidental login when in certain containers.

**Comment by mnoorenberghe** [comment]
Thanks. This is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1537631
